### ISSUE TITLE
Change HALCYON_NO_BUILD_LAYERS to HALCYON_NO_BUILD_DEPENDENCIES

### ISSUE THREAD

**Issue by mithrandi** [mietek/haskell-on-heroku#40]
It seems this environment variable was renamed in Halcyon, but this buildpack was not yet updated.

**Comment by mietek** [comment]
Thanks. This is now fixed in https://github.com/mietek/haskell-on-heroku/commit/915a09719c79d588b00916f3e52e2343340b3e2f.
