### ISSUE TITLE
Deployment error: `ERROR: Failed to detect label`

### ISSUE THREAD

**Issue by gsingh93** [mietek/haskell-on-heroku#42]
I'm trying to deploy a Yesod application to Heroku. I was following the instructions [here](https://haskellonheroku.com/tutorial/), but when I push, I get these errors:
```
$ git push -q heroku master
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> Haskell app detected
remote: 
remote: 
remote: -----> Welcome to Haskell on Heroku
remote:        BUILDPACK_URL:                            https://github.com/mietek/haskell-on-heroku
remote: 
remote: -----> Installing buildpack... done, 0175d0f
remote: -----> Installing Halcyon... done, 58c5492
remote: -----> Installing bashmenot... done, ec0ecb6
remote:    *** ERROR: Failed to detect label
remote:    *** ERROR: Failed to deploy app
remote: 
remote:  !     Push rejected, failed to compile Haskell app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to course-load.
remote: 
To https://git.heroku.com/course-load.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/course-load.git'
```

What do these errors mean?

**Comment by mietek** [comment]
Your Cabal package description file, `class-load.cabal`, needs to be at the top level of the repository. The error message could be better in this case.

**Comment by mietek** [comment]
The error message should now say `Failed to detect app` in such cases.

**Comment by gsingh93** [comment]
Thanks, moving the cabal file to the top level fixed it.

**Comment by gsingh93** [comment]
So I found that all my code has to be at the top level as well with my current setup. What I wanted was in my top level folder to have a README, a LICENSE, and a few other files, and then a `src` directory that contains the actual project. Is there a way for me to configure it to get this to work?

Specifically, the error I'm getting is
```
       cabal: can't find source for Application in ., dist/build/autogen
   *** ERROR: Failed to build app
   *** ERROR: Failed to build app
```

**Comment by mietek** [comment]
This is just a matter of setting up your [Cabal package description](https://www.haskell.org/cabal/users-guide/developing-packages.html#package-descriptions) correctly.  See the [Haskell Language](https://halcyon.sh/examples/#haskell-language) source code for an example.

The [`hl.cabal`](https://github.com/mietek/hl/blob/master/hl.cabal) file lets Cabal know the source code is located in the `src` subdirectory:
```
...
executable hl
  hs-source-dirs:    src/
...
```
