### ISSUE TITLE
How to build latest changes with a one-off PX dyno

### ISSUE THREAD

**Issue by gsingh93** [mietek/haskell-on-heroku#43]
I have a yesod website that builds fine locally with `cabal build`, but I can't deploy it because certain things that need to be rebuilt are cached. What I need is to deploy my changes to master without building them (because that would build on a slow dyno) and the build later on on a PX dyno. I've tried following [these](https://haskellonheroku.com/tutorial/#deploy-the-buildpack) instructions I don't get the expected lines when setting the `HALCYON_PURGE_CACHE` variable, which are:
```
   *** ERROR: Cannot build sandbox directory
   *** ERROR: Failed to deploy app
   *** ERROR: Deploying buildpack only
```
I get
```
remote:        Foundation.hs:74:37: Not in scope: ‘css_reset_css’
remote:    *** ERROR: Failed to build app
remote:    *** ERROR: Failed to deploy app
```
which is a build error that would be fixed if a complete rebuild was done. What am I doing wrong?

**Comment by mietek** [comment]
Please post your entire build log, preferably as a [gist](https://gist.github.com).

**Comment by gsingh93** [comment]
Build log: https://gist.github.com/gsingh93/51b4f5e76ce09f031395

**Comment by mietek** [comment]
The final steps of the tutorial are meant to populate your private storage, including a sandbox directory archive — but you already have it there.  The right sandbox directory archive for the current version of your app is already in your private storage, as you can see in line [233](https://gist.github.com/gsingh93/51b4f5e76ce09f031395#file-gistfile1-txt-L233), which shows Halcyon downloading it from there.

First, unset `HALCYON_PURGE_CACHE`, as it serves no purpose in your case.  Next, unset `PORT`, as [Heroku will set it for you](https://devcenter.heroku.com/articles/dynos#web-dynos).

> …which is a build error that would be fixed if a complete rebuild was done.

I don’t understand.  This looks like an error in your program.  Does your program compile on your local machine?

**Comment by gsingh93** [comment]
It compiles, but notice how the Heroku build starts from build 5 of 8. I believe step 4 of 8 is actually what's required for the build to work properly. I could delete everything in S3 and push, but that build would take forever. If I clear everything and run `heroku run -s PX build`, the build is quick but it's building what's currently on master, not the changes I've made.

**Comment by mietek** [comment]
OK.  To build your app from scratch, set [`HALCYON_APP_REBUILD`](https://halcyon.sh/reference/#halcyon_app_rebuild) to 1.

**Comment by gsingh93** [comment]
But the build that will happen won't happen on a PX server, will it?

**Comment by mietek** [comment]
Building on a PX one-off dyno is only needed to avoid running into the 15-minute Heroku build time limit.  Your sandbox is already built, and building your app should take far less time.

**Comment by gsingh93** [comment]
I see. It's working now, thank you for the help!

**Comment by mietek** [comment]
You’re welcome.

**Comment by mietek** [comment]
You’re welcome.  One last thing — you should record the constraints given after `*** WARNING: Using newest versions of all packages` in a `.halcyon/constraints` file.  Otherwise, your sandbox will become out-of-date as soon as someone uploads a new version of one of your dependencies to Hackage.

**Comment by gsingh93** [comment]
Will do, thanks.
