### ISSUE TITLE
Buildpack self-update changes .buildpack then fails

### ISSUE THREAD

**Issue by pbrisbin** [mietek/haskell-on-heroku#45]
Project: https://github.com/thoughtbot/carnival. Uses https://github.com/ddollar/heroku-buildpack-multi.

In a new shell (`heroku run bash`), the contents of `.buildpack` appear fine. Upon running `build`, the contents of `.buildpack` are changed to the buildpack-multi code and the build fails.

Here's a complete log: http://sprunge.us/FMfL

Here are the interesting lines:

```
++ url=https://github.com/ddollar/heroku-buildpack-multi.git
++ log_begin 'Self-updating buildpack...'
++ prefix_log_begin '-----> ' 'Self-updating buildpack...'
++ local now prefix
+++ bashmenot_internal_get_timestamp
+++ ((  0  ))
++ now=
++ prefix='-----> '
++ shift
++ echo -n '-----> Self-updating buildpack... '
-----> Self-updating buildpack... ++ local commit_hash
+++ git_update_into https://github.com/ddollar/heroku-buildpack-multi.git /app/.buildpack
```

I looks like you might be specifically looking at `BUILDPACK_URL` rather than just running the git reset in the directory as-is (which has the correct remote).

As a workaround, setting `BUILDPACK_NO_SELF_UPDATE=1` works.

**Comment by mietek** [comment]
Thanks. This looks like an unforeseen interaction with `heroku-buildpack-multi`. I’ll look into it soon.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
