### ISSUE TITLE
Tutorial application fails to deploy after 15m.

### ISSUE THREAD

**Issue by lodi** [mietek/haskell-on-heroku#48]
Hi, I'm having problems following the haskell-on-heroku-tutorial.  I'm on the deploy step and it times out without printing much output:
  https://gist.github.com/lodi/c35f10ceb8cfcdb92f14

The buildpack/Halcyon/bashmenot lines are printed almost instantly, but then it hangs.  The tutorial says that this step should take less than a minute as dependencies are restored from cache, but I think this process is failing and it's trying to rebuild them from scratch.  I'm new to heroku so I'm not sure how to set it up to use a more powerful dyno to do the first build.  I tried following the instructions near the bottom of the tutorial but they seem to assume that the first push will succeed.

**Comment by mietek** [comment]
Does this happen every time you try to `git push heroku master`?

**Comment by lodi** [comment]
Yes, I've tried this about a dozen times from two different machines with
the same result each time.  Also I checked that my environment is clean:

$ heroku config
=== infinite-garden-9953 Config Vars
BUILDPACK_URL: https://github.com/mietek/haskell-on-heroku

Should I attach any other information?

**Comment by mietek** [comment]
With https://github.com/mietek/bashmenot/commit/f566c8e832ff0ba1eab96e7b40b02fc3d5bdb943, this is now fixed.

The bug was introduced in https://github.com/mietek/bashmenot/commit/5b589a68d71b106d4cc6ac1777e8962d8a6c9858, 2 days ago. Sorry about that.

**Comment by mietek** [comment]
@lodi: Please try running `git push heroku master` again. This time, it should continue as described in the tutorial. Let me know if there are any other issues.

**Comment by lodi** [comment]
Yes, now it works.  Thanks for the incredibly fast response!
