### ISSUE TITLE
Improve build workflow

### ISSUE THREAD

**Issue by mietek** [mietek/haskell-on-heroku#49]
When building the app on a one-off dyno, use the Heroku API to publish and release slugs, as described in [“Creating slugs from scratch”](https://devcenter.heroku.com/articles/platform-api-deploying-slugs), instead of asking the user to:

```
$ git commit --amend --no-edit
$ git push -f heroku HEAD:master
```

CC @pbrisbin

**Comment by rehno-lindeque** [comment]
+1 on this. I'm enthusiastic about a solution with neither `--force` nor empty commits!

**Comment by pbrisbin** [comment]
Yes, this is a great idea.

Additionally (and let me know if you want a separate Issue), I've been trying to think of a way to have the build error when it does its empty-slug-you-must-build thing. I understand why it must succeed (so Heroku doesn't abort and discard the new sources, which are required to build), but it causes a few problems:

- The app is now broken until I'm able to build
- I can't automate `git push heroku || heroku run build` in my deploy scripts

So far, the only thing I can think of is to push the empty, updated source slug to private storage, then fail the build. `heroku run build` would then restore it from S3 before building.

- Heroku would abort, keeping the current version of the app working
- `git push` would exit non-zero, allowing me to script a build

WDYT?

**Comment by mietek** [comment]
@pbrisbin: Interesting idea. I haven’t considered it earlier, but I will now.

**Comment by mietek** [comment]
I’m sorry. This project is no longer maintained.
