### ISSUE TITLE
ERROR: Failed to detect app

### ISSUE THREAD

**Issue by tfausak** [mietek/haskell-on-heroku#50]
I am trying to deploy [Blunt](http://blunt.herokuapp.com/). I have previously deployed version 1.0.0 on 2015-04-11. I am now trying to deploy version 1.0.1. Not much has changed between the versions: <https://github.com/tfausak/blunt/compare/v1.0.0...v1.0.1>. In spite of that, I am getting a deploy error.

```
$ git push heroku master
Counting objects: 22, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (22/22), done.
Writing objects: 100% (22/22), 2.33 KiB | 0 bytes/s, done.
Total 22 (delta 13), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Fetching custom git buildpack... done
remote: -----> Haskell app detected
remote: 
remote: 
remote: -----> Welcome to Haskell on Heroku
remote:        HALCYON_AWS_ACCESS_KEY_ID:                (secret)
remote:        HALCYON_AWS_SECRET_ACCESS_KEY:            (secret)
remote:        HALCYON_S3_BUCKET:                        taylorfausak-halcyon
remote:        HALCYON_SANDBOX_EXTRA_APPS:               happy
remote:        PAPERTRAIL_API_TOKEN:                     (secret)
remote: 
remote: -----> Installing buildpack... done, f88763a
remote: -----> Installing Halcyon... done, 7210a8a
remote: -----> Installing bashmenot... done, 08977d6
remote:    *** ERROR: Failed to detect app
remote: 
remote:  !     Push rejected, failed to compile Haskell app
remote: 
remote: Verifying deploy...
remote: 
remote: !	Push rejected to blunt.
remote: 
To https://git.heroku.com/blunt.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/blunt.git'
```

I looked for an existing issue about this and found #42. However I *do* have `blunt.cabal` at the top level, and `cabal check` doesn't find anything wrong with it.

**Comment by tfausak** [comment]
I noticed [this line](https://github.com/tfausak/blunt/blob/v1.0.1/blunt.cabal#L15) highlighted strangely in my editor. So I [changed that line](https://github.com/tfausak/blunt/commit/01382b259b45ca108f04f70d97fbc3f2ad8793b2) and was able to deploy. 

I think you can reproduce this problem with a Cabal file that includes these lines:

```
description:
    version: anything
```

**Comment by mietek** [comment]
Thanks. This is now tracked as https://github.com/mietek/halcyon/issues/68.

**Comment by tfausak** [comment]
Thanks!
