### ISSUE TITLE
Build is rejected if license file is missing

### ISSUE THREAD

**Issue by tejon** [mietek/haskell-on-heroku#53]
Cabal gives an error message when `license-file: <file>` is specified in config but `<file>` is not present; this doesn't actually make the build fail in a local environment, but is interpreted as a build failure by haskell-on-heroku. Granted this is user error at its finest, but I think anything that won't stop `cabal run` should probably pass here too.

**Comment by mietek** [comment]
Please note that specifying a nonexistent file as the `license-file` stops `cabal copy` from succeeding:
```
$ cabal configure --prefix=/tmp/destination
Resolving dependencies...
Configuring hello-1.0...
Warning: The 'license-file' field refers to the file 'nonexistent' which does
not exist.
$ cabal build
Building hello-1.0...
Preprocessing executable 'hello' for hello-1.0...
[1 of 1] Compiling Main             ( Main.hs, dist/build/hello/hello-tmp/Main.o )
Linking dist/build/hello/hello ...
$ cabal copy
cabal: nonexistent: does not exist
$ echo $?
1
```
Since Halcyon is a currently wrapper around `cabal`, this failure is to be expected.
