### ISSUE TITLE
How to work around missing .so?

### ISSUE THREAD

**Issue by mohanzhang** [mietek/haskell-on-heroku#56]
I am using [dbmigrations](https://github.com/jtdaugherty/dbmigrations) for my database migrations. This package produces an executable called `moo` that you can invoke to perform various migration-related tasks. I reasoned that in order to have this executable available to me when I use `heroku run bash`, I had to include it as a dependency in my cabal file.

However, when I try to build on heroku, I get this error for one of dbmigrations' dependencies:

```
Configuring HDBC-sqlite3-2.3.3.1...
       setup-Simple-Cabal-1.22.2.0-x86_64-linux-ghc-7.10.1: Missing dependency on a
       foreign library:
       * Missing C library: sqlite3
       This problem can usually be solved by installing the system package that
       provides this library (you may need the "-dev" version). If the library is
       already installed but in a non-standard location then you can use the flags
       --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
```

To get around this, I used [multi buildpacks](https://github.com/ddollar/heroku-buildpack-multi) and [apt buildpack](https://github.com/heroku/heroku-buildpack-apt) so that I could `apt-get install libsqlite3-dev`. This had the result of putting libsqlite3.so in a local directory, like so (`heroku run bash`):

```
~/.apt/usr/lib/x86_64-linux-gnu $ pwd
/app/.apt/usr/lib/x86_64-linux-gnu
~/.apt/usr/lib/x86_64-linux-gnu $ ls
libsqlite3.a  libsqlite3.la  libsqlite3.so  pkgconfig
```

I thought I was in the clear, esp since `$LD_LIBRARY_PATH` is also set: 

```
~/.apt/usr/lib/x86_64-linux-gnu $ echo $LD_LIBRARY_PATH
/app/lib:/app/usr/lib:/app/ghc/usr/lib:/app/sandbox/lib:/app/sandbox/usr/lib:/app/lib/x86_64-linux-gnu:/app/usr/lib/x86_64-linux-gnu:/app/sandbox/lib/x86_64-linux-gnu:/app/sandbox/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/x86_64-linux-gnu:/app/.apt/usr/lib/i386-linux-gnu:/app/.apt/usr/lib:
```

But when I deploy, I get this error:

```
...
remote: -----> Building app
remote:        <no location info>:
remote:            ghc: panic! (the 'impossible' happened)
remote:          (GHC version 7.10.1 for x86_64-unknown-linux):
remote:        	Dynamic linker not initialised
remote:
remote:        Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug
remote:
remote:        <no location info>:
remote:            <command line>: can't load .so/.DLL for: libsqlite3.so (libsqlite3.so: cannot open shared object file: No such file or directory)
remote:    *** ERROR: Failed to build app
remote:    *** ERROR: Failed to deploy app
```

Any idea why this is happening? GHC is supposed to respect $LD_LIBRARY_PATH, right?

**Comment by mohanzhang** [comment]
*facepalm*

This was not very smart of me. `moo` accepts a connection string to any database, so I could just run it locally using the `DATABASE_URL` provided to me by heroku. Fail :(

**Comment by mietek** [comment]
For future reference: Using the `apt` buildpack is not necessary, as Halcyon wraps around `apt` and provides the [`HALCYON_SANDBOX_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_sandbox_extra_os_packages) and [`HALCYON_EXTRA_OS_PACKAGES`](https://halcyon.sh/reference/#halcyon_extra_os_packages) options, for installing build-time and run-time libraries, respectively.  See the [Haskell Language](https://halcyon.sh/examples/#haskell-language) source code for an example.
